Repository larnaa/cluecoins, pull requests merged in 2022-10, with the labels that each got.

#14 Store quotes in database in user home
  Makefile
  bluecoins.sql
  src/bluecoins_cli/cache.py
  src/bluecoins_cli/cli.py
  src/bluecoins_cli/database.py
  src/bluecoins_cli/storage.py
Labels: 🧁 improvement

#15 Account not changing after moving transaction
  src/bluecoins_cli/cli.py
  src/bluecoins_cli/database.py
Labels: 🐛 bug

#16 DB queries without f-format
  src/bluecoins_cli/database.py
Labels: 🧹 chore

#18 Adb sync
  Makefile
  poetry.lock
  pyproject.toml
  src/bluecoins_cli/adb.py
  src/bluecoins_cli/database.py
Labels: ✨ feature

#21 Integration pytermgui TUI
  src/bluecoins_cli/tui.py
Labels: ✨ feature

#23 Set variables "convert" and "archive" in TUI
  README.md
  poetry.lock
  pyproject.toml
  src/bluecoins_cli/__main__.py
  src/bluecoins_cli/adb.py
  src/bluecoins_cli/cache.py
  src/bluecoins_cli/cli.py
  src/bluecoins_cli/database.py
  src/bluecoins_cli/schema_tui.wsd
  src/bluecoins_cli/sync_manager.py
  src/bluecoins_cli/tui.py
Labels: ✨ feature
