Repository larnaa/cluecoins, pull requests merged in 2022-11, with the labels that each got.

#27 First documentation
  README.md
  docs/database.md
  docs/schema_tui.wsd
  docs/tui.md
  src/bluecoins_cli/adb.py
  src/bluecoins_cli/cli.py
  src/bluecoins_cli/database.py
  src/bluecoins_cli/storage.py
  src/bluecoins_cli/sync_manager.py
  src/bluecoins_cli/tui.py
Labels: 📖 documentation

#30 Better disclaimers and usage guide in README
  README.md
Labels: 📖 documentation

#34 Test covereage query database
  .bumpversion.cfg
  Makefile
  poetry.lock
  pyproject.toml
  src/cluecoins/cli.py
  src/cluecoins/database.py
  src/cluecoins/storage.py
  tests/conftest.py
  tests/test_bluecoins_cli.py
  tests/test_data.sql
  tests/test_query_database.py
  tests/test_storage.py
Labels: 🧹 chore, tests

#32 Set up a GitHub Actions pipeline
  .github/workflows/ci.yml
  .gitignore
  Makefile
  poetry.lock
Labels: 🚢 ci/cd

#41 Add cache test
  .github/workflows/ci.yml
  src/cluecoins/cache.py
  tests/test_cache.py
Labels: 🐧 tests
